service: harvest-glasgow-giving

provider:
  name: aws
  region: eu-west-2
  runtime: provided

plugins:
  - ./vendor/bref/bref

package:
  exclude:
    - .env.example
    - .env.local
    - .env.production
    - .gitattributes
    - .gitignore
    - .php_cs
    - .php_cs.cache
    - .phpstorm.meta.php
    - .styleci.yml
    - _ide_helper.php
    - composer.json
    - composer.lock
    - package.json
    - server.php
    - tailwind.config.js
    - webpack.mix.js
    - yarn.lock
    - node_modules/**
    - public/storage
    - storage/**
    - tests/**
    - resources/js/**
    - resources/sass/**
    - .git/**
    - deploy.sh
    - deployAssets.sh
    - deployProduction.sh
    - deployStaging.sh

functions:
  website:
    handler: public/index.php
    timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
    layers:
      - ${bref:layer.php-74-fpm}
    events:
      -   http: 'ANY /'
      -   http: 'ANY {proxy+}'
  artisan:
    handler: artisan
    timeout: 120 # in seconds
    layers:
      - ${bref:layer.php-74} # PHP
      - ${bref:layer.console} # The "console" layer

resources:
  Resources:
    # The S3 bucket that stores the assets
    Assets:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: harvest-giving
    # The policy that makes the bucket publicly readable
    AssetsBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref Assets # References the bucket we defined above
        PolicyDocument:
          Statement:
            -   Effect: Allow
                Principal: '*' # everyone
                Action: 's3:GetObject' # to read
                Resource: !Join ['/', [!GetAtt Assets.Arn, '*']] # things in the bucket
              # alternatively you can write out Resource: 'arn:aws:s3:::<bucket-name>/*'
